services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes: 
      - type: bind
        source: ./src
        target: /var/www/html:delegated
  mysql:
    image: mysql:5.7
    env_file: 
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
  artisan:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes: 
      - type: bind
        source: ./src
        target: /var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html


  # 1. docker compose run --rm composer create-project --prefer-dist laravel/laravel .
  # 2. docker compose up -d --build server
  # 3. docker compose run --rm artisan migrate